# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
# Text to speech
tts:
  - platform: google_translate

mqtt:
  discovery: true
  broker: 192.168.0.224
  birth_message:
    topic: 'hass/status'
    payload: 'online'
  will_message:
    topic: 'hass/status'
    payload: 'offline'
  
  button:
    - name: 'On'
      command_topic: "lirc/send/kuhl/on"
      unique_id: kuhl_on
    - name: 'Off'
      command_topic: "lirc/send/kuhl/off"
      unique_id: kuhl_off
  climate:
    - name: AC
      modes:
        - "off"
        - "cool"
        - "heat"
        - "fan_only"
      power_command_topic: "ac/power/set"
      mode_command_topic: "ac/mode/set"
      temperature_command_topic: "ac/temperature/set"
      current_temperature_topic: "ac/temperature/set"
      precision: 1.0
      min_temp: 60
      max_temp: 90

homeassistant:
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
          #- fd00::/8
      allow_bypass_login: true
          #- type: homeassistant
